const dict: Record<string, Record<string, string>> = {
  en: { circuit: 'The Circuit', tickets: 'TICKETS', sectorPrefix: 'Sector:', grid: 'Grid', racing: 'Racing', pitlane: 'Pit Lane', finished: 'Finished', telemetry: 'Telemetry', refreshAll: 'Refresh All', settings: 'Race Configuration', refreshCenter: 'Refresh Center', refreshAllData: 'Refresh All Data', sysHealth: 'Sys Health', trends: 'Trends', timing: 'Timing', issues: 'Issues', fuelLoad: 'Fuel Load', critical: 'CRITICAL', high: 'HIGH', nominal: 'NOMINAL', workInProgress: 'Work In Progress', capacity: 'Capacity', velocityDelta: 'Velocity Delta', tireDeg: 'Tire Deg', teamLoad: 'TEAM LOAD', legend: 'Legend', fresh: 'Fresh', used: 'Used', systemHealth: 'System Health', online: 'ONLINE', local: 'LOCAL', project: 'Project', board: 'Board', fieldMap: 'Field Map', browse: 'Browse', userScope: 'User Scope', appScope: 'App Scope', user: 'User', app: 'App', refresh: 'Refresh', diagnostics: 'Diagnostics', drs: 'DRS', enabled: 'ENABLED', safetyCar: 'Safety Car', virtualSc: 'VIRTUAL SC', clear: 'CLEAR', trackStatus: 'Track Status', yellowFlag: 'YELLOW FLAG', greenFlag: 'GREEN FLAG', raceControlFeed: 'Race Control Feed', boxboxReq: '[!] BOX BOX: INTERVENTION REQ', raceNormal: 'RACE NORMAL', systemDiagnostics: 'System Diagnostics', healthCheck: 'Health Check', platform: 'Platform', type: 'Type', fields: 'Fields', permissions: 'Permissions', userBrowseScope: 'User Browse Scope', appBrowseScope: 'App Browse Scope', sprintFieldAccess: 'Sprint Field Access', granted: 'GRANTED', denied: 'DENIED', available: 'AVAILABLE', missing: 'MISSING', status: 'Status', loading: 'Loading...', noData: 'No data', deepInspection: 'Deep Inspection', cspNonce: 'CSP Nonce', present: 'Present', fieldCache: 'Field Cache', boardFilter: 'Board Filter', filterJql: 'Filter JQL', sprintId: 'Sprint ID', forgeScopes: 'Forge Scopes', scopes: 'scopes', refreshing: 'Refreshing...', runDiagnostics: 'Run Diagnostics' },
  fr: { circuit: 'Le Circuit', tickets: 'TICKETS', sectorPrefix: 'Secteur :', grid: 'Grille', racing: 'Course', pitlane: 'Stand', finished: 'Terminé', telemetry: 'Télémetrie', refreshAll: 'Tout Actualiser', settings: 'Configuration', refreshCenter: 'Centre de Rafraîchissement', refreshAllData: 'Actualiser Toutes les Données', sysHealth: 'Santé Système', trends: 'Tendances', timing: 'Chronos', issues: 'Tickets', fuelLoad: 'Charge Carburant', critical: 'CRITIQUE', high: 'ÉLEVÉ', nominal: 'NOMINAL', workInProgress: 'En Cours', capacity: 'Capacité', velocityDelta: 'Delta de Vélocité', tireDeg: 'Usure Pneus', teamLoad: 'CHARGE ÉQUIPE', legend: 'Légende', fresh: 'Neuf', used: 'Usé', systemHealth: 'Santé du Système', online: 'EN LIGNE', local: 'LOCAL', project: 'Projet', board: 'Tableau', fieldMap: 'Champs', browse: 'Parcourir', userScope: 'Portée Utilisateur', appScope: 'Portée App', user: 'Utilisateur', app: 'App', refresh: 'Actualiser', diagnostics: 'Diagnostics', drs: 'DRS', enabled: 'ACTIF', safetyCar: 'Voiture de Sécurité', virtualSc: 'SC VIRTUEL', clear: 'LIBRE', trackStatus: 'État de la Piste', yellowFlag: 'DRAPEAU JAUNE', greenFlag: 'DRAPEAU VERT', raceControlFeed: 'Flux Race Control', boxboxReq: '[!] BOX BOX: INTERVENTION', raceNormal: 'COURSE NORMALE', systemDiagnostics: 'Diagnostics Système', healthCheck: 'Vérification Santé', platform: 'Plateforme', type: 'Type', fields: 'Champs', permissions: 'Permissions', userBrowseScope: 'Parcours Utilisateur', appBrowseScope: 'Parcours App', sprintFieldAccess: 'Accès Champ Sprint', granted: 'ACCORDÉ', denied: 'REFUSÉ', available: 'DISPONIBLE', missing: 'MANQUANT', status: 'Statut', loading: 'Chargement...', noData: 'Aucune donnée', deepInspection: 'Inspection Approfondie', cspNonce: 'CSP Nonce', present: 'Présent', fieldCache: 'Cache des Champs', boardFilter: 'Filtre du Tableau', filterJql: 'Filtre JQL', sprintId: 'ID Sprint', forgeScopes: 'Scopes Forge', scopes: 'scopes', refreshing: 'Actualisation...', runDiagnostics: 'Lancer Diagnostics' },
  es: { circuit: 'El Circuito', tickets: 'TICKETS', sectorPrefix: 'Sector:', grid: 'Parrilla', racing: 'Carrera', pitlane: 'Pit Lane', finished: 'Terminado', telemetry: 'Telemetría', refreshAll: 'Actualizar Todo', settings: 'Configuración', refreshCenter: 'Centro de Actualización', refreshAllData: 'Actualizar Todos los Datos', sysHealth: 'Salud del Sistema', trends: 'Tendencias', timing: 'Tiempos', issues: 'Tickets', fuelLoad: 'Carga de Combustible', critical: 'CRÍTICO', high: 'ALTO', nominal: 'NORMAL', workInProgress: 'Trabajo en Progreso', capacity: 'Capacidad', velocityDelta: 'Delta de Velocidad', tireDeg: 'Desgaste de Neumáticos', teamLoad: 'CARGA DEL EQUIPO', legend: 'Leyenda', fresh: 'Nuevo', used: 'Usado', systemHealth: 'Salud del Sistema', online: 'EN LÍNEA', local: 'LOCAL', project: 'Proyecto', board: 'Tablero', fieldMap: 'Mapa de Campos', browse: 'Explorar', userScope: 'Alcance Usuario', appScope: 'Alcance App', user: 'Usuario', app: 'App', refresh: 'Actualizar', diagnostics: 'Diagnóstico', drs: 'DRS', enabled: 'ACTIVADO', safetyCar: 'Coche de Seguridad', virtualSc: 'SC VIRTUAL', clear: 'LIBRE', trackStatus: 'Estado de Pista', yellowFlag: 'BANDERA AMARILLA', greenFlag: 'BANDERA VERDE', raceControlFeed: 'Feed de Race Control', boxboxReq: '[!] BOX BOX: INTERVENCIÓN', raceNormal: 'CARRERA NORMAL', systemDiagnostics: 'Diagnóstico del Sistema', healthCheck: 'Chequeo de Salud', platform: 'Plataforma', type: 'Tipo', fields: 'Campos', permissions: 'Permisos', userBrowseScope: 'Alcance Navegación Usuario', appBrowseScope: 'Alcance Navegación App', sprintFieldAccess: 'Acceso Campo Sprint', granted: 'CONCEDIDO', denied: 'DENEGADO', available: 'DISPONIBLE', missing: 'FALTANTE', status: 'Estado', loading: 'Cargando...', noData: 'Sin datos', deepInspection: 'Inspección Profunda', cspNonce: 'CSP Nonce', present: 'Presente', fieldCache: 'Cache de Campos', boardFilter: 'Filtro del Tablero', filterJql: 'JQL del Filtro', sprintId: 'ID de Sprint', forgeScopes: 'Scopes Forge', scopes: 'scopes', refreshing: 'Actualizando...', runDiagnostics: 'Ejecutar Diagnóstico' },
  pt: { circuit: 'O Circuito', tickets: 'TICKETS', sectorPrefix: 'Setor:', grid: 'Grid', racing: 'Corrida', pitlane: 'Pit Lane', finished: 'Concluído', telemetry: 'Telemetria', refreshAll: 'Atualizar Tudo', settings: 'Configuração', refreshCenter: 'Centro de Atualização', refreshAllData: 'Atualizar Todos os Dados', sysHealth: 'Saúde do Sistema', trends: 'Tendências', timing: 'Tempos', issues: 'Tickets', fuelLoad: 'Carga de Combustível', critical: 'CRÍTICO', high: 'ALTO', nominal: 'NORMAL', workInProgress: 'Em Progresso', capacity: 'Capacidade', velocityDelta: 'Delta de Velocidade', tireDeg: 'Desgaste do Pneu', teamLoad: 'CARGA DA EQUIPE', legend: 'Legenda', fresh: 'Novo', used: 'Usado', systemHealth: 'Saúde do Sistema', online: 'ONLINE', local: 'LOCAL', project: 'Projeto', board: 'Quadro', fieldMap: 'Mapa de Campos', browse: 'Explorar', userScope: 'Escopo Usuário', appScope: 'Escopo App', user: 'Usuário', app: 'App', refresh: 'Atualizar', diagnostics: 'Diagnóstico', drs: 'DRS', enabled: 'ATIVADO', safetyCar: 'Carro de Segurança', virtualSc: 'SC VIRTUAL', clear: 'LIVRE', trackStatus: 'Estado da Pista', yellowFlag: 'BANDEIRA AMARELA', greenFlag: 'BANDEIRA VERDE', raceControlFeed: 'Feed Race Control', boxboxReq: '[!] BOX BOX: INTERVENÇÃO', raceNormal: 'CORRIDA NORMAL', systemDiagnostics: 'Diagnóstico do Sistema', healthCheck: 'Verificação de Saúde', platform: 'Plataforma', type: 'Tipo', fields: 'Campos', permissions: 'Permissões', userBrowseScope: 'Escopo de Navegação Usuário', appBrowseScope: 'Escopo de Navegação App', sprintFieldAccess: 'Acesso ao Campo Sprint', granted: 'CONCEDIDO', denied: 'NEGADO', available: 'DISPONÍVEL', missing: 'AUSENTE', status: 'Status', loading: 'Carregando...', noData: 'Sem dados', deepInspection: 'Inspeção Profunda', cspNonce: 'CSP Nonce', present: 'Presente', fieldCache: 'Cache de Campos', boardFilter: 'Filtro do Quadro', filterJql: 'JQL do Filtro', sprintId: 'ID do Sprint', forgeScopes: 'Scopes Forge', scopes: 'scopes', refreshing: 'Atualizando...', runDiagnostics: 'Executar Diagnóstico' }
}

export function t(key: string, locale: string = 'en') {
  const l = dict[locale] ? locale : 'en'
  return dict[l][key] || key
}
// ensure keys used in panels exist
; (() => {
  const ensure = (loc: string, entries: Record<string, string>) => { dict[loc] = { ...(dict[loc] || {}), ...entries } }
  ensure('en', { telemetryFeed: 'Telemetry Feed', connected: 'CONNECTED', offline: 'OFFLINE', receivingData: 'Receiving Data', noSignal: 'No Signal', allCarsTx: 'All cars transmitting telemetry', connectDevops: 'Connect Bitbucket, GitHub, or GitLab\nto receive code telemetry' })
  ensure('en', { performanceTrends: 'Performance Trends', wipTrend: 'WIP Trend', velocity: 'Velocity' })
  ensure('en', { flow: 'FLOW', sprint: 'SPRINT', refreshTelemetry: 'Refresh Telemetry', refreshTiming: 'Refresh Timing', connectionLost: 'Connection Lost', noSprintIssues: 'No issues assigned to the active sprint', noBoardIssues: 'No issues on this board', emptyStateDesc: 'Create your first issue in Jira to see telemetry and the track map.', error: 'Error', initializingTelemetry: 'INITIALIZING TELEMETRY...', close: 'Close', unmappedTransitions: 'Transitions outside board columns' })
  ensure('en', { controls: 'CONTROLS', strategyCall: 'Strategy Call:', esc: 'ESC', driver: 'Driver', status: 'Status', priority: 'Priority', stalled: 'STALLED', high: 'HIGH', raceEngineerAnalysis: 'Race Engineer Analysis', selectStrategy: 'Select Strategy', assigneeTeamOrders: 'Assignee (Team Orders)', splitTicket: 'The Undercut', splitTicketDesc: 'Split ticket into smaller subtasks for faster sector times.', teamOrders: 'Team Orders', teamOrdersDesc: 'Reassign to senior driver with more track experience.', retireCar: 'Retire Car', retireCarDesc: 'Move to backlog. Save engine for next race.' })
  ensure('en', { detectedBoard: 'Detected Board', wipLimitLabel: 'WIP Limit (Fuel Capacity)', wipLimitDesc: 'Maximum tickets allowed in progress before overload warning.', ticketsUnit: 'tickets', assigneeCapacityLabel: 'Assignee Capacity (Tire Load)', assigneeCapacityDesc: 'Max tickets per person before burnout warning triggers.', ticketsPerPersonUnit: 'tickets/person', stalledThresholdLabel: 'Stalled Threshold (Pit Window)', stalledThresholdDesc: 'Hours without update before triggering BOX BOX alert.', recommendedRange: 'Recommended 8–72h', hoursUnit: 'hours', language: 'Language', languageDesc: 'Select UI language. Defaults to Jira preference when available.', perTypeThresholdsLabel: 'Per-Issuetype Stalled Thresholds', perTypeThresholdsDesc: 'Override stalled hours per issuetype. Empty type or non-positive hours are ignored.', issuetypePlaceholder: 'Issuetype (e.g., Bug)', remove: 'Remove', addIssuetypeRule: 'Add Issuetype Rule', duplicateIssuetypeEntries: 'Duplicate issuetype entries:', applySettings: 'Apply Settings', resetDefaults: 'Reset Defaults', system: 'System', replayBriefing: 'Missed the briefing? Replay the onboarding tour.', replayDriverBriefing: 'Replay Driver Briefing 🏁', kanbanModeDesc: 'Kanban mode: No sprints, continuous flow monitoring.', scrumModeDesc: 'Scrum mode: Tracking active sprint progress.', sprint: 'Sprint', epic: 'Epic' })
  ensure('en', { avgLapTime: 'Avg Lap Time', sectorTimes: 'Sector Times', cycleBadge: 'CYCLE', avg: 'avg', driverLapTimes: 'Driver Lap Times', lapsBadge: 'LAPS', tickets: 'tickets', best: 'best' })
  ensure('en', {
    glossary: 'Terminology Mapping', termF1: 'F1 Term', termAgile: 'Agile/Lean Term',
    g_downforce: 'Downforce', g_downforce_desc: 'Team Velocity / Throughput',
    g_fuel: 'Fuel Load', g_fuel_desc: 'Work In Progress (WIP)',
    g_tire: 'Tire Degradation', g_tire_desc: 'Team Burnout / Fatigue',
    g_grid: 'Starting Grid', g_grid_desc: 'Sprint Backlog',
    g_safetycar: 'Safety Car', g_safetycar_desc: 'Impediment / Blocker',
    g_boxbox: 'Box Box', g_boxbox_desc: 'Critical Intervention Required',
    g_pitstop: 'Pit Stop', g_pitstop_desc: 'Process Improvement / Retrospective',
    g_blueflag: 'Blue Flag', g_blueflag_desc: 'Priority Escalation',
    g_sectors: 'Track Sectors', g_sectors_desc: 'Workflow Columns / States'
  })

  ensure('fr', {
    glossary: 'Lexique F1 / Agile', termF1: 'Terme F1', termAgile: 'Terme Agile/Lean',
    g_downforce: 'Appui Aéro (Downforce)', g_downforce_desc: 'Vélocité / Débit',
    g_fuel: 'Carburant', g_fuel_desc: 'Tâches en Cours (WIP)',
    g_tire: 'Dégradation Pneus', g_tire_desc: 'Fatigue Équipe',
    g_grid: 'Grille de Départ', g_grid_desc: 'Sprint Backlog',
    g_safetycar: 'Safety Car', g_safetycar_desc: 'Bloquant / Obstacle',
    g_boxbox: 'Box Box', g_boxbox_desc: 'Intervention Critique Requise',
    g_pitstop: 'Arrêt au Stand', g_pitstop_desc: 'Amélioration / Rétrospective',
    g_blueflag: 'Drapeau Bleu', g_blueflag_desc: 'Escalade de Priorité',
    g_sectors: 'Secteurs', g_sectors_desc: 'Colonnes / États du Flux'
  })

  ensure('es', {
    glossary: 'Mapa de Terminología', termF1: 'Término F1', termAgile: 'Término Agile/Lean',
    g_downforce: 'Carga Aero (Downforce)', g_downforce_desc: 'Velocidad / Rendimiento',
    g_fuel: 'Combustible', g_fuel_desc: 'Trabajo en Progreso (WIP)',
    g_tire: 'Degradación Neumáticos', g_tire_desc: 'Fatiga del Equipo',
    g_grid: 'Parrilla de Salida', g_grid_desc: 'Sprint Backlog',
    g_safetycar: 'Safety Car', g_safetycar_desc: 'Impedimento / Bloqueo',
    g_boxbox: 'Box Box', g_boxbox_desc: 'Intervención Crítica',
    g_pitstop: 'Pit Stop', g_pitstop_desc: 'Mejora de Proceso / Retrospectiva',
    g_blueflag: 'Bandera Azul', g_blueflag_desc: 'Escalada de Prioridad',
    g_sectors: 'Sectores', g_sectors_desc: 'Columnas / Estados'
  })

  ensure('pt', {
    glossary: 'Mapeamento de Termos', termF1: 'Termo F1', termAgile: 'Termo Agile/Lean',
    g_downforce: 'Downforce', g_downforce_desc: 'Velocidade / Vazão',
    g_fuel: 'Combustível', g_fuel_desc: 'Trabalho em Progresso (WIP)',
    g_tire: 'Desgaste Pneus', g_tire_desc: 'Fadiga da Equipe',
    g_grid: 'Grid de Largada', g_grid_desc: 'Sprint Backlog',
    g_safetycar: 'Safety Car', g_safetycar_desc: 'Impedimento / Bloqueio',
    g_boxbox: 'Box Box', g_boxbox_desc: 'Intervenção Crítica',
    g_pitstop: 'Pit Stop', g_pitstop_desc: 'Melhoria de Processo / Retrospectiva',
    g_blueflag: 'Bandeira Azul', g_blueflag_desc: 'Escalada de Prioridade',
    g_sectors: 'Setores', g_sectors_desc: 'Colunas / Estados'
  })
  ensure('fr', { telemetryFeed: 'Flux de Télémétrie', connected: 'CONNECTÉ', offline: 'HORS LIGNE', receivingData: 'Réception de Données', noSignal: 'Pas de Signal', allCarsTx: 'Toutes les voitures transmettent la télémétrie', connectDevops: 'Connectez Bitbucket, GitHub ou GitLab\npour recevoir la télémétrie de code' })
  ensure('fr', { performanceTrends: 'Tendances de Performance', wipTrend: 'Tendance WIP', velocity: 'Vélocité' })
  ensure('fr', { flow: 'FLUX', sprint: 'SPRINT', refreshTelemetry: 'Actualiser Télémetrie', refreshTiming: 'Actualiser Chronos', connectionLost: 'Connexion perdue', noSprintIssues: "Aucun ticket assigné au sprint actif", noBoardIssues: 'Aucun ticket sur ce tableau', emptyStateDesc: 'Créez votre premier ticket dans Jira pour voir la télémétrie et la carte.', error: 'Erreur', initializingTelemetry: 'INITIALISATION DE LA TÉLÉMÉTRIE...', close: 'Fermer', unmappedTransitions: 'Transitions hors colonas configuradas' })
  ensure('fr', { controls: 'CONTRÔLES', strategyCall: 'Appel de Stratégie :', esc: 'ESC', driver: 'Pilote', status: 'Statut', priority: 'Priorité', stalled: 'EN PANNE', high: 'ÉLEVÉE', raceEngineerAnalysis: "Analyse de l'Ingénieur de Course", selectStrategy: 'Sélectionner Stratégie', assigneeTeamOrders: 'Assigné (Team Orders)', splitTicket: 'The Undercut', splitTicketDesc: 'Diviser en sous-tâches pour accélérer les secteurs.', teamOrders: 'Team Orders', teamOrdersDesc: 'Réassigner à un senior expérimenté.', retireCar: 'Retirer la Voiture', retireCarDesc: 'Mettre au backlog. Sauver le moteur pour la prochaine course.' })
  ensure('fr', { detectedBoard: 'Tableau détecté', wipLimitLabel: 'Limite WIP (Capacité Carburant)', wipLimitDesc: 'Nombre maximum de tickets en cours avant alerte.', ticketsUnit: 'tickets', assigneeCapacityLabel: 'Capacité Assigné (Charge Pneus)', assigneeCapacityDesc: 'Tickets max par personne avant alerte de surcharge.', ticketsPerPersonUnit: 'tickets/personne', stalledThresholdLabel: 'Seuil de Blocage (Fenêtre Stand)', stalledThresholdDesc: 'Heures sans mise à jour avant alerte BOX BOX.', recommendedRange: 'Recommandé 8–72h', hoursUnit: 'heures', language: 'Langue', languageDesc: 'Sélection de la langue. Par défaut: préférence Jira.', perTypeThresholdsLabel: 'Seuils par type de ticket', perTypeThresholdsDesc: 'Remplacer le seuil par type de ticket.', issuetypePlaceholder: 'Type (ex: Bug)', remove: 'Supprimer', addIssuetypeRule: 'Ajouter une règle', duplicateIssuetypeEntries: 'Doublons de types :', applySettings: 'Appliquer', resetDefaults: 'Réinitialiser', system: 'Système', replayBriefing: "Briefing manqué ? Rejouer l'onboarding.", replayDriverBriefing: 'Rejouer le Briefing 🏁', kanbanModeDesc: 'Mode Kanban : pas de sprints, flux continu.', scrumModeDesc: 'Mode Scrum : suivi du sprint actif.', sprint: 'Sprint', epic: 'Épopée' })
  ensure('fr', { avgLapTime: 'Temps au Tour Moyen', sectorTimes: 'Temps par Secteur', cycleBadge: 'CYCLE', avg: 'moy', driverLapTimes: 'Temps des Pilotes', lapsBadge: 'TOURS', tickets: 'tickets', best: 'meilleur' })
  ensure('es', { telemetryFeed: 'Feed de Telemetría', connected: 'CONECTADO', offline: 'SIN CONEXIÓN', receivingData: 'Recibiendo Datos', noSignal: 'Sin Señal', allCarsTx: 'Todos los coches transmitiendo telemetría', connectDevops: 'Conecte Bitbucket, GitHub o GitLab\npara recibir telemetría de código' })
  ensure('es', { performanceTrends: 'Tendencias de Rendimiento', wipTrend: 'Tendencia WIP', velocity: 'Velocidad' })
  ensure('es', { flow: 'FLUJO', sprint: 'SPRINT', refreshTelemetry: 'Actualizar Telemetría', refreshTiming: 'Actualizar Tiempos', connectionLost: 'Conexión perdida', noSprintIssues: 'No hay tickets asignados al sprint activo', noBoardIssues: 'No hay tickets en este tablero', emptyStateDesc: 'Crea tu primer ticket en Jira para ver la telemetría y el mapa.', error: 'Error', initializingTelemetry: 'INICIALIZANDO TELEMETRÍA...', close: 'Cerrar', unmappedTransitions: 'Transiciones fuera de columnas configuradas' })
  ensure('es', { controls: 'CONTROLES', strategyCall: 'Llamada de Estrategia:', esc: 'ESC', driver: 'Piloto', status: 'Estado', priority: 'Prioridad', stalled: 'DETENIDO', high: 'ALTA', raceEngineerAnalysis: 'Análisis del Ingeniero', selectStrategy: 'Seleccionar Estrategia', assigneeTeamOrders: 'Asignado (Team Orders)', splitTicket: 'The Undercut', splitTicketDesc: 'Dividir el ticket en subtareas para acelerar.', teamOrders: 'Team Orders', teamOrdersDesc: 'Reasignar a un senior con experiencia.', retireCar: 'Retirar Coche', retireCarDesc: 'Mover al backlog. Guardar motor para próxima carrera.' })
  ensure('es', { detectedBoard: 'Tablero detectado', wipLimitLabel: 'Límite WIP (Capacidad Combustible)', wipLimitDesc: 'Máximo de tickets en progreso antes de alerta.', ticketsUnit: 'tickets', assigneeCapacityLabel: 'Capacidad Asignado (Carga Neumático)', assigneeCapacityDesc: 'Máx tickets por persona antes de alerta.', ticketsPerPersonUnit: 'tickets/persona', stalledThresholdLabel: 'Umbral de Bloqueo (Ventana Box)', stalledThresholdDesc: 'Horas sin actualización antes alerta BOX BOX.', recommendedRange: 'Recomendado 8–72h', hoursUnit: 'horas', language: 'Idioma', languageDesc: 'Selecciona idioma; por defecto el de Jira.', perTypeThresholdsLabel: 'Umbrales por tipo', perTypeThresholdsDesc: 'Sobrescribir horas por tipo.', issuetypePlaceholder: 'Tipo (ej., Bug)', remove: 'Eliminar', addIssuetypeRule: 'Añadir regla', duplicateIssuetypeEntries: 'Duplicados de tipos:', applySettings: 'Aplicar', resetDefaults: 'Restablecer', system: 'Sistema', replayBriefing: '¿Perdiste el briefing? Reproduce el onboarding.', replayDriverBriefing: 'Reproducir Briefing 🏁', kanbanModeDesc: 'Kanban: sin sprints, flujo continuo.', scrumModeDesc: 'Scrum: seguimiento del sprint activo.', sprint: 'Sprint', epic: 'Épica' })
  ensure('es', { avgLapTime: 'Tiempo Medio por Vuelta', sectorTimes: 'Tiempos por Sector', cycleBadge: 'CICLO', avg: 'med', driverLapTimes: 'Tiempos de Pilotos', lapsBadge: 'VUELTAS', tickets: 'tickets', best: 'mejor' })
  ensure('pt', { telemetryFeed: 'Feed de Telemetria', connected: 'CONECTADO', offline: 'OFFLINE', receivingData: 'Recebendo Dados', noSignal: 'Sem Sinal', allCarsTx: 'Todos os carros transmitindo telemetria', connectDevops: 'Conecte Bitbucket, GitHub ou GitLab\npara receber telemetria de código' })
  ensure('pt', { performanceTrends: 'Tendências de Desempenho', wipTrend: 'Tendência WIP', velocity: 'Velocidade' })
  ensure('pt', { flow: 'FLUXO', sprint: 'SPRINT', refreshTelemetry: 'Atualizar Telemetria', refreshTiming: 'Atualizar Tempos', connectionLost: 'Conexão perdida', noSprintIssues: 'Nenhum ticket atribuído ao sprint ativo', noBoardIssues: 'Nenhum ticket neste quadro', emptyStateDesc: 'Crie seu primeiro ticket no Jira para ver a telemetria e o mapa.', error: 'Erro', initializingTelemetry: 'INICIALIZANDO TELEMETRIA...', close: 'Fechar', unmappedTransitions: 'Transições fora das colunas configuradas' })
  ensure('pt', { controls: 'CONTROLES', strategyCall: 'Chamada de Estratégia:', esc: 'ESC', driver: 'Piloto', status: 'Status', priority: 'Prioridade', stalled: 'PARADO', high: 'ALTA', raceEngineerAnalysis: 'Análise do Engenheiro de Corrida', selectStrategy: 'Selecionar Estratégia', assigneeTeamOrders: 'Designado (Team Orders)', splitTicket: 'The Undercut', splitTicketDesc: 'Dividir o ticket em subtarefas para acelerar.', teamOrders: 'Team Orders', teamOrdersDesc: 'Reatribuir a um sênior experiente.', retireCar: 'Retirar Carro', retireCarDesc: 'Mover para backlog. Salvar motor para a próxima corrida.' })
  ensure('pt', { detectedBoard: 'Quadro detectado', wipLimitLabel: 'Limite WIP (Capacidade de Combustível)', wipLimitDesc: 'Máximo de tickets em progresso antes de alerta.', ticketsUnit: 'tickets', assigneeCapacityLabel: 'Capacidade por Pessoa (Carga do Pneu)', assigneeCapacityDesc: 'Máx tickets por pessoa antes de alerta.', ticketsPerPersonUnit: 'tickets/pessoa', stalledThresholdLabel: 'Limite de Paralisação (Janela do Pit)', stalledThresholdDesc: 'Horas sem atualização antes do alerta BOX BOX.', recommendedRange: 'Recomendado 8–72h', hoursUnit: 'horas', language: 'Idioma', languageDesc: 'Selecione idioma; padrão: Jira.', perTypeThresholdsLabel: 'Limites por Tipo', perTypeThresholdsDesc: 'Substituir horas por tipo.', issuetypePlaceholder: 'Tipo (ex.: Bug)', remove: 'Remover', addIssuetypeRule: 'Adicionar regra', duplicateIssuetypeEntries: 'Tipos duplicados:', applySettings: 'Aplicar', resetDefaults: 'Redefinir', system: 'Sistema', replayBriefing: 'Perdeu o briefing? Reproduza o onboarding.', replayDriverBriefing: 'Reproduzir Briefing 🏁', kanbanModeDesc: 'Kanban: sem sprints, fluxo contínuo.', scrumModeDesc: 'Scrum: acompanhamento do sprint ativo.', sprint: 'Sprint', epic: 'Épico' })
  ensure('pt', { avgLapTime: 'Tempo Médio por Volta', sectorTimes: 'Tempos por Setor', cycleBadge: 'CICLO', avg: 'méd', driverLapTimes: 'Tempos dos Pilotos', lapsBadge: 'VOLTAS', tickets: 'tickets', best: 'melhor' })
})()
